import express from "express";
import cors from "cors";
import multer from "multer";
import pkg from "pg";

const { Pool } = pkg;

const app = express();

// --------------------
// MULTER CONFIG - Enhanced with validation
// --------------------
const storage = multer.memoryStorage();
const upload = multer({
  storage,
  limits: {
    fileSize: 5 * 1024 * 1024, // 5MB limit
  },
  fileFilter: (req, file, cb) => {
    const allowedTypes = ['image/jpeg', 'image/png', 'image/jpg', 'image/webp'];
    if (allowedTypes.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error('Invalid file type. Only JPEG, PNG, and WebP images are allowed.'));
    }
  }
});

app.use(cors({ origin: "*", allowedHeaders: ["*"] }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// --------------------
// PostgreSQL
// --------------------
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

// Test database connection
pool.on('connect', () => {
  console.log('✅ Database connected');
});

pool.on('error', (err) => {
  console.error('❌ Database connection error:', err);
});

// --------------------
// AUTO CREATE TABLE
// --------------------
async function initDB() {
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS students (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR NOT NULL,
        roll_no INTEGER NOT NULL UNIQUE,
        photo BYTEA,
        amount NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
        class_level VARCHAR(2) NOT NULL CHECK (class_level IN ('10','12')),
        subjects TEXT[] NOT NULL CHECK (array_length(subjects, 1) BETWEEN 1 AND 2),
        category VARCHAR NOT NULL,
        dob DATE NOT NULL,
        rating INTEGER NOT NULL CHECK (rating BETWEEN 0 AND 5),
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
      )
    `);

    // Create index for faster queries
    await pool.query(`
      CREATE INDEX IF NOT EXISTS idx_students_roll_no ON students(roll_no);
      CREATE INDEX IF NOT EXISTS idx_students_class ON students(class_level);
      CREATE INDEX IF NOT EXISTS idx_students_category ON students(category);
    `);

    console.log("✅ students table ready with indexes");
  } catch (err) {
    console.error("❌ Database initialization error:", err);
    process.exit(1);
  }
}

initDB();

// --------------------
// VALIDATION HELPERS
// --------------------
function validateStudentData(data) {
  const errors = [];

  if (!data.name || data.name.trim().length < 2) {
    errors.push("Name must be at least 2 characters");
  }

  if (!data.roll || isNaN(parseInt(data.roll)) || parseInt(data.roll) <= 0) {
    errors.push("Invalid roll number");
  }

  if (!data.amount || isNaN(parseFloat(data.amount)) || parseFloat(data.amount) < 0) {
    errors.push("Invalid amount");
  }

  if (!['10', '12'].includes(data.class_level)) {
    errors.push("Class must be 10 or 12");
  }

  const subjectList = Array.isArray(data.subjects) ? data.subjects : (data.subjects || "").split(",");
  if (subjectList.length < 1 || subjectList.length > 2) {
    errors.push("Must select 1-2 subjects");
  }

  if (!data.category || !['General', 'OBC', 'SC', 'ST'].includes(data.category)) {
    errors.push("Invalid category");
  }

  if (!data.dob || isNaN(Date.parse(data.dob))) {
    errors.push("Invalid date of birth");
  }

  const rating = parseInt(data.rating);
  if (isNaN(rating) || rating < 0 || rating > 5) {
    errors.push("Rating must be between 0 and 5");
  }

  return errors;
}

// Sanitize string input
function sanitize(str) {
  if (!str) return '';
  return str.toString().trim();
}

// --------------------
// HEALTH CHECK
// --------------------
app.get("/health", async (req, res) => {
  try {
    await pool.query('SELECT 1');
    res.json({ 
      status: "ok", 
      database: "connected",
      timestamp: new Date().toISOString()
    });
  } catch (err) {
    res.status(503).json({ 
      status: "error", 
      database: "disconnected",
      message: err.message 
    });
  }
});

// --------------------
// CREATE STUDENT (POST)
// --------------------
app.post("/api/submit", upload.single("photo"), async (req, res) => {
  try {
    const {
      name,
      roll,
      amount,
      class_level,
      subjects,
      category,
      dob,
      rating
    } = req.body;

    // Validate required fields
    const validationErrors = validateStudentData(req.body);
    if (validationErrors.length > 0) {
      return res.status(400).json({ 
        error: "Validation failed", 
        details: validationErrors 
      });
    }

    // Validate photo
    if (!req.file) {
      return res.status(400).json({ error: "Photo is required" });
    }

    const subjectList = Array.isArray(subjects)
      ? subjects.map(s => sanitize(s))
      : subjects.split(",").map(s => sanitize(s));

    const result = await pool.query(
      `
      INSERT INTO students
      (name, roll_no, photo, amount, class_level, subjects, category, dob, rating)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
      RETURNING id, name, roll_no, class_level, category, created_at
      `,
      [
        sanitize(name),
        parseInt(roll),
        req.file.buffer,
        parseFloat(amount),
        class_level,
        subjectList,
        category,
        dob,
        parseInt(rating)
      ]
    );

    res.status(201).json({ 
      success: true, 
      message: "Student registered successfully",
      student: result.rows[0]
    });
  }
  catch (err) {
    console.error("Submit error:", err);

    if (err.code === "23505") {
      return res.status(409).json({ 
        error: "Roll number already exists",
        code: "DUPLICATE_ROLL"
      });
    }

    if (err.message.includes('Invalid file type')) {
      return res.status(400).json({ error: err.message });
    }

    res.status(500).json({ 
      error: "Database error",
      message: process.env.NODE_ENV === 'development' ? err.message : undefined
    });
  }
});

// --------------------
// GET ALL STUDENTS (with pagination & filters)
// --------------------
app.get("/api/students", async (req, res) => {
  try {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 10;
    const offset = (page - 1) * limit;
    
    const classFilter = req.query.class;
    const categoryFilter = req.query.category;
    const searchTerm = req.query.search;

    let query = 'SELECT id, name, roll_no, amount, class_level, subjects, category, dob, rating, created_at, updated_at FROM students WHERE 1=1';
    let countQuery = 'SELECT COUNT(*) FROM students WHERE 1=1';
    const params = [];
    let paramCount = 0;

    // Build dynamic query based on filters
    if (classFilter && ['10', '12'].includes(classFilter)) {
      paramCount++;
      query += ` AND class_level = $${paramCount}`;
      countQuery += ` AND class_level = $${paramCount}`;
      params.push(classFilter);
    }

    if (categoryFilter && ['General', 'OBC', 'SC', 'ST'].includes(categoryFilter)) {
      paramCount++;
      query += ` AND category = $${paramCount}`;
      countQuery += ` AND category = $${paramCount}`;
      params.push(categoryFilter);
    }

    if (searchTerm) {
      paramCount++;
      query += ` AND (name ILIKE $${paramCount} OR CAST(roll_no AS TEXT) LIKE $${paramCount})`;
      countQuery += ` AND (name ILIKE $${paramCount} OR CAST(roll_no AS TEXT) LIKE $${paramCount})`;
      params.push(`%${searchTerm}%`);
    }

    query += ` ORDER BY created_at DESC LIMIT $${paramCount + 1} OFFSET $${paramCount + 2}`;
    params.push(limit, offset);

    const [students, total] = await Promise.all([
      pool.query(query, params),
      pool.query(countQuery, params.slice(0, paramCount))
    ]);

    const totalCount = parseInt(total.rows[0].count);
    const totalPages = Math.ceil(totalCount / limit);

    res.json({
      success: true,
      data: students.rows,
      pagination: {
        page,
        limit,
        total: totalCount,
        totalPages,
        hasNext: page < totalPages,
        hasPrev: page > 1
      }
    });
  } catch (err) {
    console.error("Get students error:", err);
    res.status(500).json({ error: "Failed to fetch students" });
  }
});

// --------------------
// GET SINGLE STUDENT BY ID
// --------------------
app.get("/api/students/:id", async (req, res) => {
  try {
    const { id } = req.params;

    if (isNaN(parseInt(id))) {
      return res.status(400).json({ error: "Invalid student ID" });
    }

    const result = await pool.query(
      'SELECT id, name, roll_no, amount, class_level, subjects, category, dob, rating, created_at, updated_at FROM students WHERE id = $1',
      [parseInt(id)]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Student not found" });
    }

    res.json({
      success: true,
      data: result.rows[0]
    });
  } catch (err) {
    console.error("Get student error:", err);
    res.status(500).json({ error: "Failed to fetch student" });
  }
});

// --------------------
// GET STUDENT PHOTO BY ID
// --------------------
app.get("/api/students/:id/photo", async (req, res) => {
  try {
    const { id } = req.params;

    if (isNaN(parseInt(id))) {
      return res.status(400).json({ error: "Invalid student ID" });
    }

    const result = await pool.query(
      'SELECT photo FROM students WHERE id = $1',
      [parseInt(id)]
    );

    if (result.rows.length === 0 || !result.rows[0].photo) {
      return res.status(404).json({ error: "Photo not found" });
    }

    res.set('Content-Type', 'image/jpeg');
    res.send(result.rows[0].photo);
  } catch (err) {
    console.error("Get photo error:", err);
    res.status(500).json({ error: "Failed to fetch photo" });
  }
});

// --------------------
// UPDATE STUDENT
// --------------------
app.put("/api/students/:id", upload.single("photo"), async (req, res) => {
  try {
    const { id } = req.params;

    if (isNaN(parseInt(id))) {
      return res.status(400).json({ error: "Invalid student ID" });
    }

    // Check if student exists
    const existing = await pool.query('SELECT id FROM students WHERE id = $1', [parseInt(id)]);
    if (existing.rows.length === 0) {
      return res.status(404).json({ error: "Student not found" });
    }

    const {
      name,
      roll,
      amount,
      class_level,
      subjects,
      category,
      dob,
      rating
    } = req.body;

    // Validate if data provided
    if (name || roll || amount || class_level || subjects || category || dob || rating !== undefined) {
      const validationErrors = validateStudentData({
        name: name || "Valid Name",
        roll: roll || "1",
        amount: amount || "0",
        class_level: class_level || "10",
        subjects: subjects || ["Math"],
        category: category || "General",
        dob: dob || "2000-01-01",
        rating: rating !== undefined ? rating : "3"
      });

      // Only check relevant fields
      const relevantErrors = validationErrors.filter(err => {
        if (!name && err.includes("Name")) return false;
        if (!roll && err.includes("roll")) return false;
        if (!amount && err.includes("amount")) return false;
        return true;
      });

      if (relevantErrors.length > 0 && Object.keys(req.body).length > 0) {
        return res.status(400).json({ 
          error: "Validation failed", 
          details: relevantErrors 
        });
      }
    }

    // Build update query dynamically
    const updates = [];
    const values = [];
    let paramCount = 0;

    if (name) {
      paramCount++;
      updates.push(`name = $${paramCount}`);
      values.push(sanitize(name));
    }
    if (roll) {
      paramCount++;
      updates.push(`roll_no = $${paramCount}`);
      values.push(parseInt(roll));
    }
    if (amount) {
      paramCount++;
      updates.push(`amount = $${paramCount}`);
      values.push(parseFloat(amount));
    }
    if (class_level) {
      paramCount++;
      updates.push(`class_level = $${paramCount}`);
      values.push(class_level);
    }
    if (subjects) {
      paramCount++;
      const subjectList = Array.isArray(subjects) 
        ? subjects.map(s => sanitize(s))
        : subjects.split(",").map(s => sanitize(s));
      updates.push(`subjects = $${paramCount}`);
      values.push(subjectList);
    }
    if (category) {
      paramCount++;
      updates.push(`category = $${paramCount}`);
      values.push(category);
    }
    if (dob) {
      paramCount++;
      updates.push(`dob = $${paramCount}`);
      values.push(dob);
    }
    if (rating !== undefined) {
      paramCount++;
      updates.push(`rating = $${paramCount}`);
      values.push(parseInt(rating));
    }
    if (req.file) {
      paramCount++;
      updates.push(`photo = $${paramCount}`);
      values.push(req.file.buffer);
    }

    if (updates.length === 0) {
      return res.status(400).json({ error: "No fields to update" });
    }

    // Add updated_at
    paramCount++;
    updates.push(`updated_at = $${paramCount}`);
    values.push(new Date());

    // Add ID for WHERE clause
    paramCount++;
    values.push(parseInt(id));

    const query = `
      UPDATE students 
      SET ${updates.join(', ')}
      WHERE id = $${paramCount}
      RETURNING id, name, roll_no, class_level, category, updated_at
    `;

    const result = await pool.query(query, values);

    res.json({
      success: true,
      message: "Student updated successfully",
      student: result.rows[0]
    });
  } catch (err) {
    console.error("Update error:", err);

    if (err.code === "23505") {
      return res.status(409).json({ 
        error: "Roll number already exists",
        code: "DUPLICATE_ROLL"
      });
    }

    res.status(500).json({ error: "Failed to update student" });
  }
});

// --------------------
// DELETE STUDENT
// --------------------
app.delete("/api/students/:id", async (req, res) => {
  try {
    const { id } = req.params;

    if (isNaN(parseInt(id))) {
      return res.status(400).json({ error: "Invalid student ID" });
    }

    const result = await pool.query(
      'DELETE FROM students WHERE id = $1 RETURNING id, name',
      [parseInt(id)]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Student not found" });
    }

    res.json({
      success: true,
      message: "Student deleted successfully",
      deleted: result.rows[0]
    });
  } catch (err) {
    console.error("Delete error:", err);
    res.status(500).json({ error: "Failed to delete student" });
  }
});

// --------------------
// STATISTICS ENDPOINT
// --------------------
app.get("/api/statistics", async (req, res) => {
  try {
    const stats = await pool.query(`
      SELECT 
        COUNT(*) as total_students,
        COUNT(CASE WHEN class_level = '10' THEN 1 END) as class_10_count,
        COUNT(CASE WHEN class_level = '12' THEN 1 END) as class_12_count,
        COUNT(CASE WHEN category = 'General' THEN 1 END) as general_count,
        COUNT(CASE WHEN category = 'OBC' THEN 1 END) as obc_count,
        COUNT(CASE WHEN category = 'SC' THEN 1 END) as sc_count,
        COUNT(CASE WHEN category = 'ST' THEN 1 END) as st_count,
        AVG(rating)::NUMERIC(3,2) as avg_rating,
        SUM(amount)::NUMERIC(10,2) as total_amount,
        AVG(amount)::NUMERIC(10,2) as avg_amount
      FROM students
    `);

    res.json({
      success: true,
      statistics: stats.rows[0]
    });
  } catch (err) {
    console.error("Statistics error:", err);
    res.status(500).json({ error: "Failed to fetch statistics" });
  }
});

// --------------------
// SEARCH STUDENTS
// --------------------
app.get("/api/students/search/:query", async (req, res) => {
  try {
    const { query } = req.params;

    if (!query || query.trim().length < 1) {
      return res.status(400).json({ error: "Search query required" });
    }

    const result = await pool.query(
      `SELECT id, name, roll_no, class_level, category, created_at 
       FROM students 
       WHERE name ILIKE $1 OR CAST(roll_no AS TEXT) LIKE $1
       ORDER BY name
       LIMIT 20`,
      [`%${query}%`]
    );

    res.json({
      success: true,
      results: result.rows,
      count: result.rows.length
    });
  } catch (err) {
    console.error("Search error:", err);
    res.status(500).json({ error: "Search failed" });
  }
});

// --------------------
// ERROR HANDLING MIDDLEWARE
// --------------------
app.use((err, req, res, next) => {
  console.error("Error:", err);

  if (err instanceof multer.MulterError) {
    if (err.code === 'LIMIT_FILE_SIZE') {
      return res.status(400).json({ 
        error: 'File size too large',
        message: 'Maximum file size is 5MB'
      });
    }
    return res.status(400).json({ error: err.message });
  }

  res.status(500).json({ 
    error: 'Internal server error',
    message: process.env.NODE_ENV === 'development' ? err.message : undefined
  });
});

// --------------------
// 404 HANDLER
// --------------------
app.use((req, res) => {
  res.status(404).json({ 
    error: 'Not found',
    message: `Route ${req.method} ${req.path} not found`
  });
});

// --------------------
// GRACEFUL SHUTDOWN
// --------------------
process.on('SIGTERM', async () => {
  console.log('SIGTERM received, closing server...');
  await pool.end();
  process.exit(0);
});

process.on('SIGINT', async () => {
  console.log('SIGINT received, closing server...');
  await pool.end();
  process.exit(0);
});

// --------------------
// START SERVER
// --------------------
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 Server running on port ${PORT}`);
  console.log(`📊 Environment: ${process.env.NODE_ENV || 'development'}`);
});