import express from "express";
import cors from "cors";
import multer from "multer";
import pkg from "pg";

const { Pool } = pkg;

const app = express();
const upload = multer();

app.use(cors({ origin: "*", allowedHeaders: ["*"] }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// --------------------
// PostgreSQL
// --------------------
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

// --------------------
// AUTO CREATE TABLE
// --------------------
async function initDB() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS students (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR NOT NULL,
      roll_no INTEGER NOT NULL UNIQUE,
      photo BYTEA,
      amount NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
      class_level VARCHAR(2) NOT NULL CHECK (class_level IN ('10','12')),
      subjects TEXT[] NOT NULL CHECK (array_length(subjects, 1) BETWEEN 1 AND 2),
      category VARCHAR NOT NULL,
      dob DATE NOT NULL,
      rating INTEGER NOT NULL CHECK (rating BETWEEN 0 AND 5),
      created_at TIMESTAMPTZ DEFAULT now()
    )
  `);

  console.log("✅ students table ready");
}

initDB();

// --------------------
// HEALTH
// --------------------
app.get("/health", (req, res) => {
  res.json({ status: "ok" });
});

// --------------------
// SUBMIT
// --------------------
app.post("/api/submit", upload.single("photo"), async (req, res) => {
  try {
    const {
      name,
      roll,
      amount,
      class_level,
      subjects,
      category,
      dob,
      rating
    } = req.body;

    if (!name || !roll || !amount || !class_level || !subjects || !category || !dob || rating === undefined) {
      return res.status(400).json({ error: "Missing fields" });
    }

    const subjectList = Array.isArray(subjects)
      ? subjects
      : subjects.split(",");

    if (subjectList.length > 2) {
      return res.status(400).json({ error: "Only 2 subjects allowed" });
    }

    await pool.query(
      `
      INSERT INTO students
      (name, roll_no, photo, amount, class_level, subjects, category, dob, rating)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
      `,
      [
        name,
        parseInt(roll),
        req.file?.buffer || null,
        parseFloat(amount),
        class_level,
        subjectList,
        category,
        dob,
        parseInt(rating)
      ]
    );

    res.json({ success: true });
  }
  catch (err) {
    console.error(err);

    if (err.code === "23505") {
      return res.status(409).json({ error: "Roll number already exists" });
    }

    res.status(500).json({ error: "Database error" });
  }
});

// --------------------
// START
// --------------------
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Server running on", PORT));
